---
kind: pipeline
name: build

steps:
- name: build
  image: archlinux/base:latest
  environment:
    TAG: "dotdc/archlinux-cicd:latest"
    TOKEN:
      from_secret: dockerhub_token
  commands:
    - pacman -Sy --noconfirm docker
    - docker login -u dotdc -p"${TOKEN}"
    - docker build -t "${TAG}" .
    - docker push "${TAG}"