---
kind: pipeline
type: docker
name: build

steps:
- name: build
  image: plugins/docker
  environment:
    TAG: "dotdc/archlinux-cicd:latest"
    TOKEN:
      from_secret: dockerhub_token
  settings:
    username: dotdc
    password: $TOKEN
    repo: dotdc/archlinux-cicd
    tags: latest