---
kind: pipeline
type: docker
name: build

steps:
- name: build
  image: plugins/docker
  environment:
    TAG: "dotdc/archlinux-cicd:latest"
  settings:
    username: dotdc
    password:
      from_secret: dockerhub_token
    repo: dotdc/archlinux-cicd
    tags: latest